### ISSUE TITLE
Breaks if pagination is activated

### ISSUE THREAD

**Issue by kenkendk** [meterup/github-release#1]
Since the Github API returns full paths for the `next` links, these cause invalid urls to be generated if the repository has many items.

You can test with:
```
> github-release info --user duplicati --repo duplicati
error: could not fetch tags, Get https://api.github.comhttps//api.github.com/repositories/22636263/tags?per_page=100&page=2: dial tcp: lookup api.github.comhttps: no such host
```

I have filed a proposed fix for the rest package here:
https://github.com/kevinburke/rest/issues/8

The full link url is returned here:
https://github.com/meterup/github-release/blob/master/github/github.go#L244

Then the REST client is created here:
https://github.com/meterup/github-release/blob/master/github/github.go#L249

But this fails as the client has a base URL and does string concatenation:
https://github.com/kevinburke/rest/blob/master/client.go#L131

It _could_ also be fixed in `github.go` by stripping the link and only passing the path part to the REST client, similar to this:

```
if strings.HasPrefix(nextLinkURL, c.client.Base) {
	nextLinkURL = nextLinkURL[len(c.client.Base):]
}
```

This also works, but is less robust, as Github _could_ send out pagination links to another domain at some point. Not sure it you would rather wait for the rest package to be fixed or include a workaround in your package.

**Comment by kevinburke** [comment]
Thanks, I can reproduce!

**Comment by kevinburke1** [comment]
This should be fixed now, please let me know if you're still running into issues.
